[package]
name = "unicore_keys"
version = "0.1.0"
authors = ["carlosgj94 <carlosgj94@gmail.com>"]

[dependencies]
base58 = "0.1"
eth-secp256k1 = { git = "https://github.com/ethcore/rust-secp256k1" }
unicore_primitives = { path = "../primitives" }
